SUPABASE_URL = "https://hjmeykckkgcmyqqvjyyy.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqbWV5a2Nra2djbXlxcXZqeXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5NjkwMTgsImV4cCI6MjA3NjU0NTAxOH0.5_zuYPpJrTABe1BueNBFcFkiWVONc7EVoxewrLWBrjM"

# Choisis l’un des deux modes d’envoi :
# (A) SMTP (ex: Gmail avec mot de passe d’application)
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 465
SMTP_USER = "abdelilah.benchine3@gmail.com"
SMTP_PASSWORD = "vqhsomzuzfyakzff"

# (B) API e-mail (ex: Resend)
RESEND_API_KEY = ""
RESEND_FROM = "Toi <noreply@ton-domaine.tld>"